package nginx

import (
	"fmt"
	"strings"

	"github.com/mizanproxy/mizan/internal/ir"
	"github.com/mizanproxy/mizan/internal/translate"
)

func Generate(m *ir.Model) translate.Result {
	var b strings.Builder
	var sm []translate.SourceMapEntry
	var warnings []translate.Warning
	line := 1
	add := func(entityID, s string) {
		start := line
		b.WriteString(s)
		if !strings.HasSuffix(s, "\n") {
			b.WriteByte('\n')
		}
		line += strings.Count(s, "\n")
		if !strings.HasSuffix(s, "\n") {
			line++
		}
		if entityID != "" {
			sm = append(sm, translate.SourceMapEntry{StartLine: start, EndLine: line - 1, EntityID: entityID})
		}
	}

	add("", "# Generated by Mizan. Do not edit by hand unless you plan to re-import.")
	add("", "events {}\n\nhttp {\n")

	for _, cache := range m.Caches {
		add(cache.ID, fmt.Sprintf("  proxy_cache_path %s keys_zone=%s:10m max_size=%s inactive=60m use_temp_path=off;\n", cache.Path, cache.Zone, defaultString(cache.MaxSize, "1g")))
	}

	for _, be := range m.Backends {
		var lines strings.Builder
		lines.WriteString(fmt.Sprintf("  upstream %s {\n", be.ID))
		if be.Algorithm == "leastconn" || be.Algorithm == "least_conn" {
			lines.WriteString("    least_conn;\n")
		}
		for _, srv := range serversForBackend(m, be) {
			weight := srv.Weight
			if weight == 0 {
				weight = 100
			}
			lines.WriteString(fmt.Sprintf("    server %s:%d weight=%d", srv.Address, srv.Port, weight))
			if srv.MaxConn > 0 {
				lines.WriteString(fmt.Sprintf(" max_conns=%d", srv.MaxConn))
			}
			lines.WriteString(";\n")
		}
		lines.WriteString("  }\n\n")
		add(be.ID, lines.String())
	}

	for _, fe := range m.Frontends {
		var lines strings.Builder
		lines.WriteString("  server {\n")
		listen := listenPort(fe.Bind)
		lines.WriteString("    listen " + listen)
		if fe.TLSID != "" {
			lines.WriteString(" ssl")
		}
		if strings.EqualFold(fe.Protocol, "http2") {
			lines.WriteString(" http2")
		}
		lines.WriteString(";\n")
		if tls := findTLS(m, fe.TLSID); tls != nil {
			lines.WriteString("    ssl_certificate " + tls.CertPath + ";\n")
			if tls.KeyPath != "" {
				lines.WriteString("    ssl_certificate_key " + tls.KeyPath + ";\n")
			}
		}
		for _, ruleID := range fe.Rules {
			rule := findRule(m, ruleID)
			if rule == nil || rule.Action.Type != "use_backend" {
				continue
			}
			path := "/"
			if rule.Predicate.Type == "path_prefix" || rule.Predicate.Type == "path" {
				path = rule.Predicate.Value
			}
			lines.WriteString(fmt.Sprintf("    location %s {\n      proxy_pass http://%s;\n    }\n", path, rule.Action.BackendID))
		}
		if fe.DefaultBackend != "" {
			lines.WriteString(fmt.Sprintf("    location / {\n      proxy_pass http://%s;\n    }\n", fe.DefaultBackend))
		}
		lines.WriteString("  }\n\n")
		add(fe.ID, lines.String())
	}

	for _, rl := range m.RateLimits {
		warnings = append(warnings, translate.Warning{EntityID: rl.ID, Message: "rate limit rendering is basic; attach it in an Nginx location before production use"})
	}

	add("", "}\n")
	return translate.Result{Target: ir.EngineNginx, Config: b.String(), SourceMap: sm, Warnings: warnings}
}

func defaultString(v, fallback string) string {
	if v == "" {
		return fallback
	}
	return v
}

func listenPort(bind string) string {
	if strings.Contains(bind, ":") {
		parts := strings.Split(bind, ":")
		if last := parts[len(parts)-1]; last != "" {
			return last
		}
	}
	return bind
}

func findTLS(m *ir.Model, id string) *ir.TLSProfile {
	for i := range m.TLSProfiles {
		if m.TLSProfiles[i].ID == id {
			return &m.TLSProfiles[i]
		}
	}
	return nil
}

func findRule(m *ir.Model, id string) *ir.Rule {
	for i := range m.Rules {
		if m.Rules[i].ID == id {
			return &m.Rules[i]
		}
	}
	return nil
}

func serversForBackend(m *ir.Model, be ir.Backend) []ir.Server {
	allowed := map[string]bool{}
	for _, id := range be.Servers {
		allowed[id] = true
	}
	var out []ir.Server
	for _, srv := range m.Servers {
		if allowed[srv.ID] {
			out = append(out, srv)
		}
	}
	return out
}
