package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestRunVersionAndUnknown(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"version"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("mizan")) {
		t.Fatalf("unexpected version output: %s", stdout.String())
	}
	if err := Run(context.Background(), []string{"nope"}, &stdout, &stderr); err == nil {
		t.Fatal("expected unknown command error")
	}
}

func TestServeInvalidBindReturnsError(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), []string{"serve", "--home", t.TempDir(), "--bind", "bad address"}, &stdout, &stderr)
	if err == nil {
		t.Fatal("expected serve error for invalid bind")
	}
}

func TestProjectGenerateValidateAndSnapshotCommands(t *testing.T) {
	home := t.TempDir()
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"project", "new", "--home", home, "--name", "edge", "--engines", "haproxy,nginx"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	if created.Project.ID == "" {
		t.Fatal("missing project id")
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"project", "list", "--home", home}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("edge")) {
		t.Fatalf("project list missing edge: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"generate", "--home", home, "--project", created.Project.ID, "--target", "haproxy"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("Generated by Mizan")) {
		t.Fatalf("generate output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"validate", "--home", home, "--project", created.Project.ID, "--target", "haproxy"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte(`"target":"haproxy"`)) {
		t.Fatalf("validate output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "list", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var snapshots []string
	if err := json.Unmarshal(stdout.Bytes(), &snapshots); err != nil {
		t.Fatal(err)
	}
	if len(snapshots) == 0 {
		t.Fatal("expected snapshots")
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "tag", "--home", home, "--project", created.Project.ID, "--label", "release", snapshots[0]}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "get", "--home", home, "--project", created.Project.ID, "release"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "revert", "--home", home, "--project", created.Project.ID, "release"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "tags", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("release")) {
		t.Fatalf("tags output unexpected: %s", stdout.String())
	}
}

func TestProjectImportAndDelete(t *testing.T) {
	home := t.TempDir()
	cfgPath := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := os.WriteFile(cfgPath, []byte("frontend web\n  bind :80\n  default_backend be_app\nbackend be_app\n  server app 127.0.0.1:8080\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"project", "import", "--home", home, "--name", "imported", cfgPath}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	if err := Run(context.Background(), []string{"project", "delete", "--home", home, created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
}

func TestCLIErrorBranches(t *testing.T) {
	home := t.TempDir()
	var stdout, stderr bytes.Buffer
	expectErr := func(args ...string) {
		t.Helper()
		stdout.Reset()
		stderr.Reset()
		if err := Run(context.Background(), args, &stdout, &stderr); err == nil {
			t.Fatalf("expected error for args %v", args)
		}
	}

	rootFile := filepath.Join(t.TempDir(), "root-file")
	if err := os.WriteFile(rootFile, []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	badCfg := filepath.Join(t.TempDir(), "bad.txt")
	if err := os.WriteFile(badCfg, []byte("not a config"), 0o600); err != nil {
		t.Fatal(err)
	}
	goodCfg := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := os.WriteFile(goodCfg, []byte("frontend web\n  bind :80\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	expectErr("serve", "--bad")
	expectErr("serve", "--home", rootFile)
	expectErr("project")
	expectErr("project", "new", "--bad")
	expectErr("project", "new", "--home", home)
	expectErr("project", "new", "--home", rootFile, "--name", "bad")
	expectErr("project", "list", "--bad")
	expectErr("project", "list", "--home", rootFile)
	expectErr("project", "delete", "--bad")
	expectErr("project", "delete", "--home", home)
	expectErr("project", "import", "--bad")
	expectErr("project", "import", "--home", home)
	expectErr("project", "import", "--home", home, filepath.Join(t.TempDir(), "missing.cfg"))
	expectErr("project", "import", "--home", home, badCfg)
	expectErr("project", "import", "--home", rootFile, goodCfg)
	expectErr("project", "unknown")

	expectErr("snapshot")
	expectErr("snapshot", "list", "--bad")
	expectErr("snapshot", "list", "--home", home)
	expectErr("snapshot", "get", "--bad")
	expectErr("snapshot", "get", "--home", home)
	expectErr("snapshot", "get", "--home", home, "--project", "p_1", "missing")
	expectErr("snapshot", "revert", "--bad")
	expectErr("snapshot", "revert", "--home", home)
	expectErr("snapshot", "revert", "--home", home, "--project", "p_1", "missing")
	expectErr("snapshot", "tag", "--bad")
	expectErr("snapshot", "tag", "--home", home)
	expectErr("snapshot", "tag", "--home", home, "--project", "p_1", "--label", "release", "missing")
	expectErr("snapshot", "tags", "--bad")
	expectErr("snapshot", "tags", "--home", home)
	expectErr("snapshot", "unknown")

	expectErr("generate", "--bad")
	expectErr("generate", "--home", home)
	expectErr("generate", "--home", home, "--project", "missing")
	expectErr("validate", "--bad")
	expectErr("validate", "--home", home)
	expectErr("validate", "--home", home, "--project", "missing")

	stdout.Reset()
	if err := Run(context.Background(), []string{"project", "new", "--home", home, "positional"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	expectErr("generate", "--home", home, "--project", created.Project.ID, "--target", "bad")
	expectErr("validate", "--home", home, "--project", created.Project.ID, "--target", "bad")

	outPath := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := Run(context.Background(), []string{"generate", "--home", home, "--project", created.Project.ID, "--out", outPath}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if data, err := os.ReadFile(outPath); err != nil || !bytes.Contains(data, []byte("Generated by Mizan")) {
		t.Fatalf("unexpected generated file data=%q err=%v", string(data), err)
	}
	expectErr("generate", "--home", home, "--project", created.Project.ID, "--out", filepath.Join(t.TempDir(), "missing", "x.cfg"))
}

func TestParseEngines(t *testing.T) {
	engines := parseEngines("haproxy,nginx,bad")
	if len(engines) != 2 {
		t.Fatalf("engines=%v", engines)
	}
}
