package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"os"
	"path/filepath"
	"testing"

	"github.com/mizanproxy/mizan/internal/store"
)

func TestRunVersionAndUnknown(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"version"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("mizan")) {
		t.Fatalf("unexpected version output: %s", stdout.String())
	}
	if err := Run(context.Background(), []string{"nope"}, &stdout, &stderr); err == nil {
		t.Fatal("expected unknown command error")
	}
}

func TestServeInvalidBindReturnsError(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), []string{"serve", "--home", t.TempDir(), "--bind", "bad address"}, &stdout, &stderr)
	if err == nil {
		t.Fatal("expected serve error for invalid bind")
	}
}

func TestRunDefaultServeStopsCleanly(t *testing.T) {
	oldListenAndServe := listenAndServe
	t.Cleanup(func() { listenAndServe = oldListenAndServe })
	listenAndServe = func(*http.Server) error {
		return http.ErrServerClosed
	}
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), nil, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("Mizan serving")) {
		t.Fatalf("unexpected serve output: %s", stdout.String())
	}
}

func TestProjectGenerateValidateAndSnapshotCommands(t *testing.T) {
	home := t.TempDir()
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"project", "new", "--home", home, "--name", "edge", "--engines", "haproxy,nginx"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	if created.Project.ID == "" {
		t.Fatal("missing project id")
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"project", "list", "--home", home}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("edge")) {
		t.Fatalf("project list missing edge: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"generate", "--home", home, "--project", created.Project.ID, "--target", "haproxy"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("Generated by Mizan")) {
		t.Fatalf("generate output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"validate", "--home", home, "--project", created.Project.ID, "--target", "haproxy"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte(`"target":"haproxy"`)) {
		t.Fatalf("validate output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"target", "add", "--home", home, "--project", created.Project.ID, "--name", "edge-01", "--host", "lb1.example.com", "--engine", "haproxy", "--sudo", "--post-reload-probe", "https://edge.example.com/healthz"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var target store.Target
	if err := json.Unmarshal(stdout.Bytes(), &target); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"target", "add", "--home", home, "--project", created.Project.ID, "--id", target.ID, "--name", "edge-01b", "--host", "lb1.example.com", "--engine", "nginx", "--config-path", "/etc/nginx/nginx.conf", "--reload-command", "systemctl reload nginx"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("edge-01b")) {
		t.Fatalf("target update output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"target", "list", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("edge-01b")) {
		t.Fatalf("target list output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"cluster", "add", "--home", home, "--project", created.Project.ID, "--name", "prod", "--target-ids", target.ID, "--parallelism", "2"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var cluster store.Cluster
	if err := json.Unmarshal(stdout.Bytes(), &cluster); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"cluster", "add", "--home", home, "--project", created.Project.ID, "--id", cluster.ID, "--name", "prod-b", "--target-ids", target.ID, "--gate-on-failure=false"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("prod-b")) {
		t.Fatalf("cluster update output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"cluster", "list", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("prod-b")) {
		t.Fatalf("cluster list output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"deploy", "--home", home, "--project", created.Project.ID, "--target-id", target.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte(`"dry_run":true`)) || !bytes.Contains(stdout.Bytes(), []byte(`"target_id":"`+target.ID+`"`)) {
		t.Fatalf("deploy target output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"deploy", "--home", home, "--project", created.Project.ID, "--cluster-id", cluster.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte(`"cluster_id":"`+cluster.ID+`"`)) {
		t.Fatalf("deploy cluster output unexpected: %s", stdout.String())
	}
	st := store.New(home)
	events, err := st.ListAudit(context.Background(), created.Project.ID, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(events) != 2 || events[0].Action != "deploy.run" || events[0].Actor != "cli" {
		t.Fatalf("unexpected deploy audit events: %+v", events)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "list", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var snapshots []string
	if err := json.Unmarshal(stdout.Bytes(), &snapshots); err != nil {
		t.Fatal(err)
	}
	if len(snapshots) == 0 {
		t.Fatal("expected snapshots")
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "tag", "--home", home, "--project", created.Project.ID, "--label", "release", snapshots[0]}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "get", "--home", home, "--project", created.Project.ID, "release"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "revert", "--home", home, "--project", created.Project.ID, "release"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"snapshot", "tags", "--home", home, "--project", created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stdout.Bytes(), []byte("release")) {
		t.Fatalf("tags output unexpected: %s", stdout.String())
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"cluster", "delete", "--home", home, "--project", created.Project.ID, cluster.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	if err := Run(context.Background(), []string{"target", "delete", "--home", home, "--project", created.Project.ID, target.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
}

func TestProjectImportAndDelete(t *testing.T) {
	home := t.TempDir()
	cfgPath := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := os.WriteFile(cfgPath, []byte("frontend web\n  bind :80\n  default_backend be_app\nbackend be_app\n  server app 127.0.0.1:8080\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	if err := Run(context.Background(), []string{"project", "import", "--home", home, "--name", "imported", cfgPath}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	if err := Run(context.Background(), []string{"project", "delete", "--home", home, created.Project.ID}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
}

func TestCLIErrorBranches(t *testing.T) {
	home := t.TempDir()
	var stdout, stderr bytes.Buffer
	expectErr := func(args ...string) {
		t.Helper()
		stdout.Reset()
		stderr.Reset()
		if err := Run(context.Background(), args, &stdout, &stderr); err == nil {
			t.Fatalf("expected error for args %v", args)
		}
	}

	rootFile := filepath.Join(t.TempDir(), "root-file")
	if err := os.WriteFile(rootFile, []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	badCfg := filepath.Join(t.TempDir(), "bad.txt")
	if err := os.WriteFile(badCfg, []byte("not a config"), 0o600); err != nil {
		t.Fatal(err)
	}
	goodCfg := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := os.WriteFile(goodCfg, []byte("frontend web\n  bind :80\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	expectErr("serve", "--bad")
	expectErr("serve", "--home", rootFile)
	expectErr("project")
	expectErr("project", "new", "--bad")
	expectErr("project", "new", "--home", home)
	expectErr("project", "new", "--home", rootFile, "--name", "bad")
	expectErr("project", "list", "--bad")
	expectErr("project", "list", "--home", rootFile)
	expectErr("project", "delete", "--bad")
	expectErr("project", "delete", "--home", home)
	expectErr("project", "import", "--bad")
	expectErr("project", "import", "--home", home)
	expectErr("project", "import", "--home", home, filepath.Join(t.TempDir(), "missing.cfg"))
	expectErr("project", "import", "--home", home, badCfg)
	expectErr("project", "import", "--home", rootFile, goodCfg)
	expectErr("project", "unknown")

	expectErr("snapshot")
	expectErr("snapshot", "list", "--bad")
	expectErr("snapshot", "list", "--home", home)
	expectErr("snapshot", "get", "--bad")
	expectErr("snapshot", "get", "--home", home)
	expectErr("snapshot", "get", "--home", home, "--project", "p_1", "missing")
	expectErr("snapshot", "revert", "--bad")
	expectErr("snapshot", "revert", "--home", home)
	expectErr("snapshot", "revert", "--home", home, "--project", "p_1", "missing")
	expectErr("snapshot", "tag", "--bad")
	expectErr("snapshot", "tag", "--home", home)
	expectErr("snapshot", "tag", "--home", home, "--project", "p_1", "--label", "release", "missing")
	expectErr("snapshot", "tags", "--bad")
	expectErr("snapshot", "tags", "--home", home)
	expectErr("snapshot", "unknown")

	expectErr("target")
	expectErr("target", "list", "--bad")
	expectErr("target", "list", "--home", home)
	expectErr("target", "list", "--home", rootFile, "--project", "p_1")
	expectErr("target", "add", "--bad")
	expectErr("target", "add", "--home", home)
	expectErr("target", "add", "--home", rootFile, "--project", "p_1", "--name", "edge", "--host", "host")
	expectErr("target", "delete", "--bad")
	expectErr("target", "delete", "--home", home)
	expectErr("target", "delete", "--home", home, "--project", "p_1", "missing")
	expectErr("target", "unknown")

	expectErr("cluster")
	expectErr("cluster", "list", "--bad")
	expectErr("cluster", "list", "--home", home)
	expectErr("cluster", "list", "--home", rootFile, "--project", "p_1")
	expectErr("cluster", "add", "--bad")
	expectErr("cluster", "add", "--home", home)
	expectErr("cluster", "add", "--home", rootFile, "--project", "p_1", "--name", "prod")
	expectErr("cluster", "delete", "--bad")
	expectErr("cluster", "delete", "--home", home)
	expectErr("cluster", "delete", "--home", home, "--project", "p_1", "missing")
	expectErr("cluster", "unknown")

	expectErr("generate", "--bad")
	expectErr("generate", "--home", home)
	expectErr("generate", "--home", home, "--project", "missing")
	expectErr("validate", "--bad")
	expectErr("validate", "--home", home)
	expectErr("validate", "--home", home, "--project", "missing")
	expectErr("deploy", "--bad")
	expectErr("deploy", "--home", home)
	expectErr("deploy", "--home", home, "--project", "missing")
	expectErr("deploy", "--home", home, "--project", "missing", "--target-id", "t_1")

	stdout.Reset()
	if err := Run(context.Background(), []string{"project", "new", "--home", home, "positional"}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	var created struct {
		Project struct {
			ID string `json:"id"`
		} `json:"project"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	expectErr("generate", "--home", home, "--project", created.Project.ID, "--target", "bad")
	expectErr("validate", "--home", home, "--project", created.Project.ID, "--target", "bad")
	expectErr("deploy", "--home", home, "--project", created.Project.ID, "--target-id", "t_1", "--cluster-id", "c_1")
	expectErr("deploy", "--home", home, "--project", created.Project.ID, "--target-id", "missing")

	outPath := filepath.Join(t.TempDir(), "haproxy.cfg")
	if err := Run(context.Background(), []string{"generate", "--home", home, "--project", created.Project.ID, "--out", outPath}, &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if data, err := os.ReadFile(outPath); err != nil || !bytes.Contains(data, []byte("Generated by Mizan")) {
		t.Fatalf("unexpected generated file data=%q err=%v", string(data), err)
	}
	expectErr("generate", "--home", home, "--project", created.Project.ID, "--out", filepath.Join(t.TempDir(), "missing", "x.cfg"))
}

func TestSnapshotInjectedStoreErrors(t *testing.T) {
	oldListSnapshots := listSnapshotsFromStore
	oldListSnapshotTags := listSnapshotTagsFromStore
	t.Cleanup(func() {
		listSnapshotsFromStore = oldListSnapshots
		listSnapshotTagsFromStore = oldListSnapshotTags
	})
	var stdout, stderr bytes.Buffer
	listSnapshotsFromStore = func(*store.Store, context.Context, string) ([]string, error) {
		return nil, errors.New("list snapshots failed")
	}
	if err := Run(context.Background(), []string{"snapshot", "list", "--home", t.TempDir(), "--project", "p_1"}, &stdout, &stderr); err == nil {
		t.Fatal("expected injected snapshot list error")
	}
	listSnapshotsFromStore = oldListSnapshots

	listSnapshotTagsFromStore = func(*store.Store, context.Context, string) ([]store.SnapshotTag, error) {
		return nil, errors.New("list tags failed")
	}
	if err := Run(context.Background(), []string{"snapshot", "tags", "--home", t.TempDir(), "--project", "p_1"}, &stdout, &stderr); err == nil {
		t.Fatal("expected injected snapshot tags error")
	}
}

func TestParseEngines(t *testing.T) {
	engines := parseEngines("haproxy,nginx,bad")
	if len(engines) != 2 {
		t.Fatalf("engines=%v", engines)
	}
	if items := splitCSV(" a, ,b "); len(items) != 2 || items[0] != "a" || items[1] != "b" {
		t.Fatalf("items=%v", items)
	}
}
