package haproxy

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mizanproxy/mizan/internal/ir"
	"github.com/mizanproxy/mizan/internal/translate"
)

func Generate(m *ir.Model) translate.Result {
	var b strings.Builder
	var sm []translate.SourceMapEntry
	line := 1
	add := func(entityID, s string) {
		start := line
		b.WriteString(s)
		if !strings.HasSuffix(s, "\n") {
			b.WriteByte('\n')
		}
		line += strings.Count(s, "\n")
		if !strings.HasSuffix(s, "\n") {
			line++
		}
		if entityID != "" {
			sm = append(sm, translate.SourceMapEntry{StartLine: start, EndLine: line - 1, EntityID: entityID})
		}
	}

	add("", "# Generated by Mizan. Do not edit by hand unless you plan to re-import.")
	add("", "global\n  log stdout format raw local0\n  maxconn 4096\n\n")
	add("", "defaults\n  log global\n  mode http\n  option httplog\n  timeout connect 5s\n  timeout client 30s\n  timeout server 30s\n\n")

	for _, fe := range m.Frontends {
		var lines strings.Builder
		lines.WriteString(fmt.Sprintf("frontend %s\n", safeName(fe.ID, fe.Name)))
		bind := fe.Bind
		if fe.TLSID != "" {
			if tls := findTLS(m, fe.TLSID); tls != nil {
				bind += fmt.Sprintf(" ssl crt %s", tls.CertPath)
				if len(tls.ALPN) > 0 {
					bind += " alpn " + strings.Join(tls.ALPN, ",")
				}
			}
		}
		lines.WriteString("  bind " + bind + "\n")
		lines.WriteString("  mode " + haproxyMode(fe.Protocol) + "\n")
		for _, ruleID := range fe.Rules {
			rule := findRule(m, ruleID)
			if rule == nil {
				continue
			}
			acl := "acl_" + rule.ID
			lines.WriteString(fmt.Sprintf("  acl %s %s\n", acl, predicate(rule.Predicate)))
			if rule.Action.Type == "use_backend" && rule.Action.BackendID != "" {
				lines.WriteString(fmt.Sprintf("  use_backend %s if %s\n", rule.Action.BackendID, acl))
			}
		}
		if fe.DefaultBackend != "" {
			lines.WriteString("  default_backend " + fe.DefaultBackend + "\n")
		}
		lines.WriteByte('\n')
		add(fe.ID, lines.String())
	}

	for _, be := range m.Backends {
		var lines strings.Builder
		lines.WriteString(fmt.Sprintf("backend %s\n", safeName(be.ID, be.Name)))
		lines.WriteString("  balance " + haproxyAlgorithm(be.Algorithm) + "\n")
		if hc := findHealth(m, be.HealthCheckID); hc != nil && hc.Type == "http" {
			path := hc.Path
			if path == "" {
				path = "/"
			}
			lines.WriteString("  option httpchk GET " + path + "\n")
		}
		servers := serversForBackend(m, be)
		sort.SliceStable(servers, func(i, j int) bool { return servers[i].ID < servers[j].ID })
		for _, srv := range servers {
			name := safeName(srv.ID, srv.Name)
			if name == "" {
				name = srv.ID
			}
			weight := srv.Weight
			if weight == 0 {
				weight = 100
			}
			lines.WriteString(fmt.Sprintf("  server %s %s:%d weight %d check", name, srv.Address, srv.Port, weight))
			if srv.MaxConn > 0 {
				lines.WriteString(fmt.Sprintf(" maxconn %d", srv.MaxConn))
			}
			lines.WriteByte('\n')
		}
		for _, ob := range m.OpaqueBlocks {
			if ob.Section == "backend "+be.ID {
				for _, opaqueLine := range ob.Lines {
					lines.WriteString("  " + opaqueLine + "\n")
				}
			}
		}
		lines.WriteByte('\n')
		add(be.ID, lines.String())
	}

	return translate.Result{Target: ir.EngineHAProxy, Config: b.String(), SourceMap: sm}
}

func safeName(id, name string) string {
	if name != "" {
		return strings.NewReplacer(" ", "_", "-", "_").Replace(name)
	}
	return id
}

func haproxyMode(protocol string) string {
	if strings.EqualFold(protocol, "tcp") {
		return "tcp"
	}
	return "http"
}

func haproxyAlgorithm(alg string) string {
	switch strings.ToLower(alg) {
	case "leastconn", "least_conn":
		return "leastconn"
	case "source", "ip_hash":
		return "source"
	default:
		return "roundrobin"
	}
}

func predicate(p ir.Predicate) string {
	switch p.Type {
	case "host":
		return "hdr(host) -i " + p.Value
	case "path":
		return "path " + p.Value
	default:
		return "path_beg " + p.Value
	}
}

func findTLS(m *ir.Model, id string) *ir.TLSProfile {
	for i := range m.TLSProfiles {
		if m.TLSProfiles[i].ID == id {
			return &m.TLSProfiles[i]
		}
	}
	return nil
}

func findRule(m *ir.Model, id string) *ir.Rule {
	for i := range m.Rules {
		if m.Rules[i].ID == id {
			return &m.Rules[i]
		}
	}
	return nil
}

func findHealth(m *ir.Model, id string) *ir.HealthCheck {
	for i := range m.HealthChecks {
		if m.HealthChecks[i].ID == id {
			return &m.HealthChecks[i]
		}
	}
	return nil
}

func serversForBackend(m *ir.Model, be ir.Backend) []ir.Server {
	allowed := map[string]bool{}
	for _, id := range be.Servers {
		allowed[id] = true
	}
	var out []ir.Server
	for _, srv := range m.Servers {
		if allowed[srv.ID] {
			out = append(out, srv)
		}
	}
	return out
}
