package deploy

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/mizanproxy/mizan/internal/ir"
	"github.com/mizanproxy/mizan/internal/store"
)

func TestRunDryTargetAndCluster(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "edge-01", Host: "lb1.example.com", Engine: ir.EngineHAProxy, PostReloadProbe: "https://edge.example.com/healthz"})
	if err != nil {
		t.Fatal(err)
	}
	cluster, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "prod", TargetIDs: []string{target.ID}, Parallelism: 2})
	if err != nil {
		t.Fatal(err)
	}
	now := time.Date(2026, 4, 26, 9, 0, 0, 0, time.UTC)
	deployer := Deployer{Now: func() time.Time { return now }}
	result, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "success" || !result.DryRun || result.StartedAt != now.Format(time.RFC3339) || len(result.Steps) != 6 {
		t.Fatalf("unexpected target deploy result: %+v", result)
	}
	if result.Steps[1].Status != "skipped" || result.Steps[1].Message != "dry run" {
		t.Fatalf("expected skipped upload step: %+v", result.Steps[1])
	}

	result, err = deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.ClusterID != cluster.ID || len(result.Steps) != 6 || result.Steps[0].Batch != 1 {
		t.Fatalf("unexpected cluster deploy result: %+v", result)
	}
}

func TestRunExecutesAndHandlesFailures(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy, ir.EngineNginx})
	if err != nil {
		t.Fatal(err)
	}
	first, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "first", Host: "first.example.com", Engine: ir.EngineHAProxy, PostReloadProbe: "https://first.example.com/healthz"})
	if err != nil {
		t.Fatal(err)
	}
	second, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "second", Host: "second.example.com", Engine: ir.EngineNginx, Sudo: true})
	if err != nil {
		t.Fatal(err)
	}
	cluster, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "prod", TargetIDs: []string{first.ID, second.ID}, Parallelism: 1, GateOnFailure: false})
	if err != nil {
		t.Fatal(err)
	}
	var ran []string
	deployer := Deployer{
		Runner: func(_ context.Context, target store.Target, command string, input string) (string, error) {
			ran = append(ran, target.Name+":"+command)
			if target.ID == first.ID && strings.Contains(command, "reload") {
				return "reload failed", errors.New("exit 1")
			}
			if input != "" && !strings.Contains(input, "Generated by Mizan") {
				t.Fatalf("generated config was not passed to upload: %q", input)
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
	}
	result, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || len(result.Steps) < 9 {
		t.Fatalf("expected failed result that continues to second target: %+v", result)
	}
	if len(ran) < 8 || !strings.Contains(result.Steps[len(result.Steps)-2].Command, "sudo sh -lc") {
		t.Fatalf("runner commands not recorded as expected: steps=%+v ran=%v", result.Steps, ran)
	}

	gated, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "gated", TargetIDs: []string{first.ID, second.ID}, Parallelism: 1, GateOnFailure: true})
	if err != nil {
		t.Fatal(err)
	}
	ran = nil
	result, err = deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: gated.ID})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || strings.Contains(strings.Join(ran, "\n"), "second:") {
		t.Fatalf("expected gated deployment to stop after first failure: %+v ran=%v", result, ran)
	}
}

func TestRunErrorsAndSelectionBranches(t *testing.T) {
	st := store.New(t.TempDir())
	deployer := Deployer{}
	for _, req := range []Request{
		{TargetID: "t_1"},
		{ProjectID: "p_1"},
		{ProjectID: "p_1", TargetID: "missing"},
	} {
		if _, err := deployer.Run(t.Context(), st, req); err == nil {
			t.Fatalf("expected error for request %+v", req)
		}
	}
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: "missing"}); err == nil {
		t.Fatal("expected missing target error")
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: "missing"}); err == nil {
		t.Fatal("expected missing cluster error")
	}
	if err := os.WriteFile(filepath.Join(st.Root(), "projects", meta.ID, "targets.json"), []byte("{"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: "missing"}); err == nil {
		t.Fatal("expected list targets error")
	}

	file := store.TargetsFile{
		Targets: []store.Target{{ID: "t_1", Name: "one"}},
		Clusters: []store.Cluster{
			{ID: "empty", Parallelism: 0},
			{ID: "bad", TargetIDs: []string{"missing"}},
			{ID: "ok", TargetIDs: []string{"t_1"}, Parallelism: 0},
		},
	}
	if _, _, _, err := selectTargets(file, Request{ClusterID: "empty"}); err == nil {
		t.Fatal("expected empty cluster error")
	}
	if _, _, _, err := selectTargets(file, Request{ClusterID: "bad"}); err == nil {
		t.Fatal("expected missing cluster target error")
	}
	selected, parallelism, gate, err := selectTargets(file, Request{ClusterID: "ok"})
	if err != nil || len(selected) != 1 || parallelism != 1 || gate {
		t.Fatalf("unexpected selection: selected=%+v parallelism=%d gate=%t err=%v", selected, parallelism, gate, err)
	}
}

func TestNewAndDefaultClock(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "edge", Host: "localhost", Engine: ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	result, err := New().Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.StartedAt == "" || result.FinishedAt == "" {
		t.Fatalf("expected timestamps from default clock: %+v", result)
	}
}

func TestRunTargetErrorAndProbeBranches(t *testing.T) {
	deployer := Deployer{
		Runner: func(context.Context, store.Target, string, string) (string, error) {
			return "ok", nil
		},
		Prober: func(context.Context, string) error {
			return errors.New("probe failed")
		},
	}
	model := ir.EmptyModel("p_1", "edge", "", []ir.Engine{ir.EngineHAProxy})
	steps := deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "bad", Engine: ir.Engine("bad")}, 1, false)
	if len(steps) != 1 || steps[0].Status != "failed" || steps[0].Message == "" {
		t.Fatalf("expected generation failure: %+v", steps)
	}
	steps = deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "edge", Engine: ir.EngineHAProxy, Host: "host", Port: 22, User: "root", ConfigPath: "/etc/haproxy/haproxy.cfg", ReloadCommand: "reload", PostReloadProbe: "https://edge.example.com/healthz"}, 1, false)
	if !hasFailed(steps) || steps[len(steps)-1].Stage != "probe" {
		t.Fatalf("expected probe failure: %+v", steps)
	}
	deployer.Prober = func(context.Context, string) error { return nil }
	steps = deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "edge", Engine: ir.EngineHAProxy, Host: "host", Port: 22, User: "root", ConfigPath: "/etc/haproxy/haproxy.cfg", ReloadCommand: "reload", PostReloadProbe: "https://edge.example.com/healthz"}, 1, false)
	if hasFailed(steps) || steps[len(steps)-1].Status != "success" {
		t.Fatalf("expected successful probe: %+v", steps)
	}
}

func TestCommandsAndHelpers(t *testing.T) {
	target := store.Target{Host: "edge.example.com", Port: 2222, User: "deployer", Engine: ir.EngineNginx, ConfigPath: "/etc/nginx/nginx.conf", ReloadCommand: "systemctl reload nginx", Sudo: true}
	if got := uploadCommand(target, "/tmp/it's.cfg"); !strings.Contains(got, "ssh -p 2222 deployer@edge.example.com") || !strings.Contains(got, "'\"'\"'") {
		t.Fatalf("unexpected upload command: %s", got)
	}
	if got := remoteValidateCommand(target, "/tmp/nginx.conf"); got != "nginx -t -c '/tmp/nginx.conf'" {
		t.Fatalf("unexpected nginx validate command: %s", got)
	}
	if got := remoteValidateCommand(store.Target{Engine: ir.EngineHAProxy}, "/tmp/haproxy.cfg"); got != "haproxy -c -f '/tmp/haproxy.cfg'" {
		t.Fatalf("unexpected haproxy validate command: %s", got)
	}
	if got := installCommand(target, "/tmp/nginx.conf"); !strings.HasPrefix(got, "sudo sh -lc ") {
		t.Fatalf("expected sudo install command: %s", got)
	}
	if stepStatus(errors.New("bad"), true) != "failed" || stepStatus(nil, true) != "success" || stepStatus(nil, false) != "success" {
		t.Fatal("unexpected step status")
	}
	if errString(nil) != "" || errString(errors.New("bad")) != "bad" {
		t.Fatal("unexpected errString")
	}
	if hasFailed([]Step{{Status: "success"}}) || !hasFailed([]Step{{Status: "failed"}}) {
		t.Fatal("unexpected hasFailed")
	}
}

func TestSSHRunnerWithFakeSSH(t *testing.T) {
	dir := t.TempDir()
	oldPath := os.Getenv("PATH")
	t.Cleanup(func() { _ = os.Setenv("PATH", oldPath) })
	script := filepath.Join(dir, "ssh")
	body := "#!/bin/sh\ncat >/dev/null\necho fake-ssh \"$@\"\n"
	if runtime.GOOS == "windows" {
		script += ".bat"
		body = "@echo off\r\nmore > nul\r\necho fake-ssh %*\r\n"
	}
	if err := os.WriteFile(script, []byte(body), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Setenv("PATH", dir+string(os.PathListSeparator)+oldPath); err != nil {
		t.Fatal(err)
	}
	out, err := sshRunner(t.Context(), store.Target{Host: "host", Port: 22, User: "root"}, "echo ok", "config")
	if err != nil || !strings.Contains(out, "fake-ssh") {
		t.Fatalf("unexpected fake ssh result out=%q err=%v", out, err)
	}
}

func TestHTTPProbe(t *testing.T) {
	if err := httpProbe(t.Context(), "://bad"); err == nil {
		t.Fatal("expected request creation error")
	}
	if err := httpProbe(t.Context(), "http://127.0.0.1:1"); err == nil {
		t.Fatal("expected connection error")
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/fail" {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()
	if err := httpProbe(t.Context(), server.URL+"/fail"); err == nil {
		t.Fatal("expected status error")
	}
	if err := httpProbe(t.Context(), server.URL+"/ok"); err != nil {
		t.Fatalf("expected successful probe: %v", err)
	}
}
