package deploy

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/mizanproxy/mizan/internal/ir"
	"github.com/mizanproxy/mizan/internal/secrets"
	"github.com/mizanproxy/mizan/internal/store"
)

func TestRunDryTargetAndCluster(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "edge-01", Host: "lb1.example.com", Engine: ir.EngineHAProxy, PostReloadProbe: "https://edge.example.com/healthz"})
	if err != nil {
		t.Fatal(err)
	}
	cluster, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "prod", TargetIDs: []string{target.ID}, Parallelism: 2})
	if err != nil {
		t.Fatal(err)
	}
	now := time.Date(2026, 4, 26, 9, 0, 0, 0, time.UTC)
	deployer := Deployer{Now: func() time.Time { return now }}
	result, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "success" || !result.DryRun || result.StartedAt != now.Format(time.RFC3339) || len(result.Steps) != 7 {
		t.Fatalf("unexpected target deploy result: %+v", result)
	}
	if result.Cleanup.Planned != 1 || result.Cleanup.Attempted != 0 {
		t.Fatalf("unexpected dry-run cleanup summary: %+v", result.Cleanup)
	}
	if result.Steps[1].Status != "skipped" || result.Steps[1].Message != "dry run" {
		t.Fatalf("expected skipped upload step: %+v", result.Steps[1])
	}
	if result.Steps[len(result.Steps)-1].Stage != "cleanup" || result.Steps[len(result.Steps)-1].Status != "skipped" {
		t.Fatalf("expected skipped cleanup step: %+v", result.Steps[len(result.Steps)-1])
	}

	result, err = deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.ClusterID != cluster.ID || len(result.Steps) != 7 || result.Steps[0].Batch != 1 {
		t.Fatalf("unexpected cluster deploy result: %+v", result)
	}
}

func TestRunExecutesAndHandlesFailures(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy, ir.EngineNginx})
	if err != nil {
		t.Fatal(err)
	}
	first, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "first", Host: "first.example.com", Engine: ir.EngineHAProxy, PostReloadProbe: "https://first.example.com/healthz"})
	if err != nil {
		t.Fatal(err)
	}
	second, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "second", Host: "second.example.com", Engine: ir.EngineNginx, Sudo: true})
	if err != nil {
		t.Fatal(err)
	}
	cluster, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "prod", TargetIDs: []string{first.ID, second.ID}, Parallelism: 1, GateOnFailure: false, RequiredApprovals: 2})
	if err != nil {
		t.Fatal(err)
	}
	_, snapshot, err := st.GetIR(t.Context(), meta.ID)
	if err != nil {
		t.Fatal(err)
	}
	var ran []string
	deployer := Deployer{
		Runner: func(_ context.Context, target store.Target, credential secrets.Secret, command string, input string) (string, error) {
			ran = append(ran, target.Name+":"+command)
			if credential.Username != "" {
				ran[len(ran)-1] += ":" + credential.Username
			}
			if target.ID == first.ID && strings.Contains(command, "reload") {
				return "reload failed", errors.New("exit 1")
			}
			if input != "" && !strings.Contains(input, "Generated by Mizan") {
				t.Fatalf("generated config was not passed to upload: %q", input)
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
		Credentials: func(_ context.Context, target store.Target) (secrets.Secret, error) {
			return secrets.Secret{Username: "vault-" + target.Name}, nil
		},
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, ConfirmSnapshotHash: snapshot, ApprovedBy: []string{"alice"}}); err == nil || !strings.Contains(err.Error(), "approval") {
		t.Fatalf("expected approval gate error, got %v", err)
	}
	result, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, ConfirmSnapshotHash: snapshot, ApprovedBy: []string{"alice", "bob", "Alice"}})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || len(result.Steps) < 9 || result.RequiredApprovals != 2 || strings.Join(result.ApprovedBy, ",") != "alice,bob" {
		t.Fatalf("expected failed result that continues to second target: %+v", result)
	}
	if result.Rollback.Planned != 0 || result.Rollback.Attempted != 0 {
		t.Fatalf("unexpected rollback stats without rollback command: %+v", result.Rollback)
	}
	if len(ran) < 8 || !strings.Contains(strings.Join(ran, "\n"), "vault-second") || result.Steps[1].Credential != "vault" || !strings.Contains(result.Steps[len(result.Steps)-2].Command, "sudo sh -lc") {
		t.Fatalf("runner commands not recorded as expected: steps=%+v ran=%v", result.Steps, ran)
	}

	gated, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "gated", TargetIDs: []string{first.ID, second.ID}, Parallelism: 1, GateOnFailure: true})
	if err != nil {
		t.Fatal(err)
	}
	ran = nil
	result, err = deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: gated.ID, ConfirmSnapshotHash: snapshot})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || strings.Contains(strings.Join(ran, "\n"), "second:") {
		t.Fatalf("expected gated deployment to stop after first failure: %+v ran=%v", result, ran)
	}

	deployer.Credentials = func(context.Context, store.Target) (secrets.Secret, error) {
		return secrets.Secret{}, errors.New("vault failed")
	}
	result, err = deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: first.ID, ConfirmSnapshotHash: snapshot})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || len(result.Steps) != 1 || result.Steps[0].Stage != "credentials" {
		t.Fatalf("expected credential failure step: %+v", result)
	}
	deployer.Credentials = func(_ context.Context, target store.Target) (secrets.Secret, error) {
		if target.ID == first.ID {
			return secrets.Secret{}, errors.New("vault failed")
		}
		return secrets.Secret{}, nil
	}
	result, err = deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, ConfirmSnapshotHash: snapshot, ApprovedBy: []string{"alice,bob"}})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || len(result.Steps) <= 1 || result.Steps[0].Stage != "credentials" {
		t.Fatalf("expected credential failure to continue in ungated cluster: %+v", result)
	}
}

func TestRunClusterBatchSelection(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	var ids []string
	for _, name := range []string{"first", "second", "third"} {
		target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: name, Host: name + ".example.com", Engine: ir.EngineHAProxy})
		if err != nil {
			t.Fatal(err)
		}
		ids = append(ids, target.ID)
	}
	cluster, err := st.UpsertCluster(t.Context(), meta.ID, store.Cluster{Name: "prod", TargetIDs: ids, Parallelism: 2, GateOnFailure: true})
	if err != nil {
		t.Fatal(err)
	}
	result, err := (Deployer{}).Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, DryRun: true, Batch: 2})
	if err != nil {
		t.Fatal(err)
	}
	if result.Batch != 2 || len(result.Steps) != 6 || result.Steps[0].TargetName != "third" || result.Steps[0].Batch != 2 {
		t.Fatalf("unexpected batch result: %+v", result)
	}
	if _, err := (Deployer{}).Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, DryRun: true, Batch: 3}); err == nil || !strings.Contains(err.Error(), "batch 3") {
		t.Fatalf("expected empty batch error, got %v", err)
	}
	if _, err := (Deployer{}).Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: cluster.ID, DryRun: true, Batch: -1}); err == nil || !strings.Contains(err.Error(), "batch") {
		t.Fatalf("expected negative batch error, got %v", err)
	}
}

func TestRunExecuteRecordsRollbackSummary(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{
		Name:            "edge",
		Host:            "edge.example.com",
		Engine:          ir.EngineHAProxy,
		RollbackCommand: "cp /etc/haproxy/haproxy.cfg.bak /etc/haproxy/haproxy.cfg && systemctl reload haproxy",
	})
	if err != nil {
		t.Fatal(err)
	}
	_, snapshot, err := st.GetIR(t.Context(), meta.ID)
	if err != nil {
		t.Fatal(err)
	}
	var commands []string
	deployer := Deployer{
		Runner: func(_ context.Context, _ store.Target, _ secrets.Secret, command string, _ string) (string, error) {
			commands = append(commands, command)
			if strings.Contains(command, "install -m") {
				return "install failed", errors.New("exit 1")
			}
			if strings.Contains(command, "cp /etc/haproxy") {
				return "rollback failed", errors.New("exit 2")
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
	}
	result, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, ConfirmSnapshotHash: snapshot})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || result.Rollback.Planned != 1 || result.Rollback.Attempted != 1 || result.Rollback.Failed != 1 || result.Rollback.Succeeded != 0 {
		t.Fatalf("unexpected rollback summary result=%+v", result)
	}
	if !strings.Contains(strings.Join(commands, "\n"), "cp /etc/haproxy") {
		t.Fatalf("rollback command was not executed: %v", commands)
	}
}

func TestRunExecuteRecordsCleanupSummary(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "edge", Host: "edge.example.com", Engine: ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	_, snapshot, err := st.GetIR(t.Context(), meta.ID)
	if err != nil {
		t.Fatal(err)
	}
	deployer := Deployer{
		Runner: func(_ context.Context, _ store.Target, _ secrets.Secret, command string, _ string) (string, error) {
			if strings.HasPrefix(command, "rm -f ") {
				return "cleanup failed", errors.New("exit 1")
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
	}
	result, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, ConfirmSnapshotHash: snapshot})
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || result.Cleanup.Planned != 1 || result.Cleanup.Attempted != 1 || result.Cleanup.Failed != 1 || result.Cleanup.Succeeded != 0 {
		t.Fatalf("unexpected cleanup summary result=%+v", result)
	}
}

func TestRunErrorsAndSelectionBranches(t *testing.T) {
	st := store.New(t.TempDir())
	deployer := Deployer{}
	for _, req := range []Request{
		{TargetID: "t_1"},
		{ProjectID: "p_1"},
		{ProjectID: "p_1", TargetID: "missing"},
	} {
		if _, err := deployer.Run(t.Context(), st, req); err == nil {
			t.Fatalf("expected error for request %+v", req)
		}
	}
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: "missing"}); err == nil {
		t.Fatal("expected missing target error")
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, ClusterID: "missing"}); err == nil {
		t.Fatal("expected missing cluster error")
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "edge", Host: "localhost", Engine: ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID}); err == nil || !strings.Contains(err.Error(), "confirm_snapshot_hash") {
		t.Fatalf("expected execute confirmation error, got %v", err)
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, ClusterID: "also-set", DryRun: true}); err == nil || !strings.Contains(err.Error(), "exactly one") {
		t.Fatalf("expected target/cluster exclusivity error, got %v", err)
	}
	if err := os.WriteFile(filepath.Join(st.Root(), "projects", meta.ID, "targets.json"), []byte("{"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := deployer.Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: "missing", DryRun: true}); err == nil {
		t.Fatal("expected list targets error")
	}

	file := store.TargetsFile{
		Targets: []store.Target{{ID: "t_1", Name: "one"}},
		Clusters: []store.Cluster{
			{ID: "empty", Parallelism: 0},
			{ID: "bad", TargetIDs: []string{"missing"}},
			{ID: "ok", TargetIDs: []string{"t_1"}, Parallelism: 0},
		},
	}
	if _, _, _, _, err := selectTargets(file, Request{ClusterID: "empty"}); err == nil {
		t.Fatal("expected empty cluster error")
	}
	if _, _, _, _, err := selectTargets(file, Request{ClusterID: "bad"}); err == nil {
		t.Fatal("expected missing cluster target error")
	}
	selected, parallelism, gate, requiredApprovals, err := selectTargets(file, Request{ClusterID: "ok"})
	if err != nil || len(selected) != 1 || parallelism != 1 || gate || requiredApprovals != 0 {
		t.Fatalf("unexpected selection: selected=%+v parallelism=%d gate=%t approvals=%d err=%v", selected, parallelism, gate, requiredApprovals, err)
	}
}

func TestNewAndDefaultClock(t *testing.T) {
	st := store.New(t.TempDir())
	meta, _, _, err := st.CreateProject(t.Context(), "edge", "", []ir.Engine{ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	target, err := st.UpsertTarget(t.Context(), meta.ID, store.Target{Name: "edge", Host: "localhost", Engine: ir.EngineHAProxy})
	if err != nil {
		t.Fatal(err)
	}
	result, err := New().Run(t.Context(), st, Request{ProjectID: meta.ID, TargetID: target.ID, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.StartedAt == "" || result.FinishedAt == "" {
		t.Fatalf("expected timestamps from default clock: %+v", result)
	}
}

func TestRunTargetErrorAndProbeBranches(t *testing.T) {
	deployer := Deployer{
		Runner: func(context.Context, store.Target, secrets.Secret, string, string) (string, error) {
			return "ok", nil
		},
		Prober: func(context.Context, string) error {
			return errors.New("probe failed")
		},
	}
	model := ir.EmptyModel("p_1", "edge", "", []ir.Engine{ir.EngineHAProxy})
	steps := deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "bad", Engine: ir.Engine("bad")}, secrets.Secret{}, 1, false)
	if len(steps) != 1 || steps[0].Status != "failed" || steps[0].Message == "" {
		t.Fatalf("expected generation failure: %+v", steps)
	}
	steps = deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "edge", Engine: ir.EngineHAProxy, Host: "host", Port: 22, User: "root", ConfigPath: "/etc/haproxy/haproxy.cfg", ReloadCommand: "reload", PostReloadProbe: "https://edge.example.com/healthz"}, secrets.Secret{}, 1, false)
	if !hasFailed(steps) || steps[1].Credential != "local_ssh" || steps[len(steps)-2].Stage != "probe" || steps[len(steps)-1].Stage != "cleanup" {
		t.Fatalf("expected probe failure: %+v", steps)
	}
	deployer.Prober = func(context.Context, string) error { return nil }
	steps = deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "edge", Engine: ir.EngineHAProxy, Host: "host", Port: 22, User: "root", ConfigPath: "/etc/haproxy/haproxy.cfg", ReloadCommand: "reload", PostReloadProbe: "https://edge.example.com/healthz"}, secrets.Secret{}, 1, false)
	if hasFailed(steps) || steps[len(steps)-1].Status != "success" {
		t.Fatalf("expected successful probe: %+v", steps)
	}
	if steps[len(steps)-1].Stage != "cleanup" || steps[len(steps)-1].Credential != "local_ssh" {
		t.Fatalf("expected cleanup success step: %+v", steps)
	}
}

func TestRunTargetRollbackHook(t *testing.T) {
	var commands []string
	deployer := Deployer{
		Runner: func(_ context.Context, _ store.Target, _ secrets.Secret, command string, _ string) (string, error) {
			commands = append(commands, command)
			if strings.Contains(command, "cp /etc/haproxy") {
				return "rollback ok", nil
			}
			if strings.Contains(command, "reload") {
				return "reload failed", errors.New("exit 1")
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
	}
	model := ir.EmptyModel("p_1", "edge", "", []ir.Engine{ir.EngineHAProxy})
	target := store.Target{
		ID:              "t_1",
		Name:            "edge",
		Engine:          ir.EngineHAProxy,
		Host:            "host",
		Port:            22,
		User:            "root",
		ConfigPath:      "/etc/haproxy/haproxy.cfg",
		ReloadCommand:   "systemctl reload haproxy",
		RollbackCommand: "cp /etc/haproxy/haproxy.cfg.bak /etc/haproxy/haproxy.cfg && systemctl reload haproxy",
		Sudo:            true,
	}
	steps := deployer.runTarget(t.Context(), model, "p_1", target, secrets.Secret{}, 1, false)
	if len(steps) < 3 || steps[len(steps)-2].Stage != "rollback" || steps[len(steps)-2].Status != "success" || steps[len(steps)-1].Stage != "cleanup" {
		t.Fatalf("expected successful rollback after reload failure: %+v", steps)
	}
	if !strings.Contains(steps[len(steps)-2].Command, "sudo sh -lc") || !strings.Contains(strings.Join(commands, "\n"), "cp /etc/haproxy") {
		t.Fatalf("rollback command was not executed with sudo: steps=%+v commands=%v", steps, commands)
	}

	steps = deployer.runTarget(t.Context(), model, "p_1", target, secrets.Secret{}, 1, true)
	if steps[len(steps)-2].Stage != "rollback" || steps[len(steps)-2].Status != "skipped" {
		t.Fatalf("expected dry-run rollback plan before cleanup: %+v", steps)
	}
	if stats := RollbackSummary(steps); stats.Planned != 1 || stats.Attempted != 0 || stats.Succeeded != 0 || stats.Failed != 0 {
		t.Fatalf("unexpected dry-run rollback summary: %+v", stats)
	}

	deployer.Runner = func(_ context.Context, _ store.Target, _ secrets.Secret, command string, _ string) (string, error) {
		if strings.Contains(command, "reload") {
			return "reload failed", errors.New("exit 1")
		}
		if strings.Contains(command, "cp /etc/haproxy") {
			return "rollback failed", errors.New("exit 2")
		}
		return "ok", nil
	}
	steps = deployer.runTarget(t.Context(), model, "p_1", target, secrets.Secret{}, 1, false)
	if steps[len(steps)-2].Stage != "rollback" || steps[len(steps)-2].Status != "failed" || steps[len(steps)-1].Stage != "cleanup" {
		t.Fatalf("expected failed rollback step: %+v", steps)
	}
	if stats := RollbackSummary(steps); stats.Planned != 1 || stats.Attempted != 1 || stats.Failed != 1 {
		t.Fatalf("unexpected failed rollback summary: %+v", stats)
	}
}

func TestRunTargetCleanupFailure(t *testing.T) {
	deployer := Deployer{
		Runner: func(_ context.Context, _ store.Target, _ secrets.Secret, command string, _ string) (string, error) {
			if strings.HasPrefix(command, "rm -f ") {
				return "cleanup failed", errors.New("exit 1")
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
	}
	model := ir.EmptyModel("p_1", "edge", "", []ir.Engine{ir.EngineHAProxy})
	steps := deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "edge", Engine: ir.EngineHAProxy, Host: "host", Port: 22, User: "root", ConfigPath: "/etc/haproxy/haproxy.cfg", ReloadCommand: "reload"}, secrets.Secret{}, 1, false)
	if !hasFailed(steps) || steps[len(steps)-1].Stage != "cleanup" || steps[len(steps)-1].Message == "" {
		t.Fatalf("expected cleanup failure: %+v", steps)
	}
}

func TestRunTargetCleansUpAfterRemoteValidationFailure(t *testing.T) {
	var commands []string
	deployer := Deployer{
		Runner: func(_ context.Context, _ store.Target, _ secrets.Secret, command string, _ string) (string, error) {
			commands = append(commands, command)
			if strings.Contains(command, "haproxy -c") {
				return "invalid config", errors.New("exit 1")
			}
			return "ok", nil
		},
		Prober: func(context.Context, string) error { return nil },
	}
	model := ir.EmptyModel("p_1", "edge", "", []ir.Engine{ir.EngineHAProxy})
	steps := deployer.runTarget(t.Context(), model, "p_1", store.Target{ID: "t_1", Name: "edge", Engine: ir.EngineHAProxy, Host: "host", Port: 22, User: "root", ConfigPath: "/etc/haproxy/haproxy.cfg", ReloadCommand: "reload"}, secrets.Secret{}, 1, false)
	if len(steps) != 4 || steps[len(steps)-2].Stage != "remote_validate" || steps[len(steps)-2].Status != "failed" || steps[len(steps)-1].Stage != "cleanup" || steps[len(steps)-1].Status != "success" {
		t.Fatalf("expected validation failure followed by cleanup: %+v", steps)
	}
	if strings.Contains(strings.Join(commands, "\n"), "install -m") {
		t.Fatalf("install should not run after validation failure: %v", commands)
	}
}

func TestRunDrill(t *testing.T) {
	report := RunDrill(t.Context())
	if report.Status != "success" || len(report.Scenarios) != 4 {
		t.Fatalf("unexpected drill report: %+v", report)
	}
	summary := SummarizeDrill(report)
	if summary.Status != "success" || summary.Totals.Scenarios != 4 || summary.Totals.FailedScenarios != 0 || summary.Totals.DeploymentFailures != 4 {
		t.Fatalf("unexpected drill summary: %+v", summary)
	}
	if summary.Totals.RollbackAttempted != 2 || summary.Totals.RollbackSucceeded != 2 || summary.Totals.CleanupAttempted != 4 || summary.Totals.CleanupFailed != 1 {
		t.Fatalf("unexpected drill summary totals: %+v", summary.Totals)
	}
	text := FormatDrillText(report)
	if !strings.Contains(text, "Mizan deploy drill: success") || !strings.Contains(text, "cleanup attempted=4 succeeded=3 failed=1") || !strings.Contains(text, "probe_failure_rolls_back_and_cleans_tmp") {
		t.Fatalf("unexpected drill text output:\n%s", text)
	}
	for _, scenario := range report.Scenarios {
		if scenario.Status != "success" || len(scenario.Steps) == 0 || len(scenario.Commands) == 0 {
			t.Fatalf("unexpected drill scenario: %+v", scenario)
		}
	}
	byName := map[string]DrillScenarioResult{}
	for _, scenario := range report.Scenarios {
		byName[scenario.Name] = scenario
	}
	if byName["remote_validation_failure_cleans_tmp"].Rollback.Planned != 0 || byName["remote_validation_failure_cleans_tmp"].Cleanup.Succeeded != 1 {
		t.Fatalf("unexpected remote validation drill summary: %+v", byName["remote_validation_failure_cleans_tmp"])
	}
	if byName["install_failure_rolls_back_and_cleans_tmp"].Rollback.Succeeded != 1 || byName["install_failure_rolls_back_and_cleans_tmp"].Cleanup.Succeeded != 1 {
		t.Fatalf("unexpected install failure drill summary: %+v", byName["install_failure_rolls_back_and_cleans_tmp"])
	}
	if byName["probe_failure_rolls_back_and_cleans_tmp"].Rollback.Succeeded != 1 || byName["probe_failure_rolls_back_and_cleans_tmp"].Cleanup.Succeeded != 1 {
		t.Fatalf("unexpected probe failure drill summary: %+v", byName["probe_failure_rolls_back_and_cleans_tmp"])
	}
	if byName["cleanup_failure_is_incident_signal"].Cleanup.Failed != 1 || byName["cleanup_failure_is_incident_signal"].DeploymentStatus != "failed" {
		t.Fatalf("unexpected cleanup failure drill summary: %+v", byName["cleanup_failure_is_incident_signal"])
	}
}

func TestDrillEvidenceValidation(t *testing.T) {
	report := RunDrill(t.Context())
	reportData, err := json.Marshal(report)
	if err != nil {
		t.Fatal(err)
	}
	summary, err := ParseDrillEvidence(reportData)
	if err != nil {
		t.Fatal(err)
	}
	if err := ValidateDrillEvidence(summary); err != nil {
		t.Fatal(err)
	}
	summaryData, err := json.Marshal(summary)
	if err != nil {
		t.Fatal(err)
	}
	parsedSummary, err := ParseDrillEvidence(summaryData)
	if err != nil {
		t.Fatal(err)
	}
	if err := ValidateDrillEvidence(parsedSummary); err != nil {
		t.Fatal(err)
	}
	parsedSummary.Totals.CleanupFailed = 0
	if err := ValidateDrillEvidence(parsedSummary); err == nil {
		t.Fatal("expected tampered drill totals to fail validation")
	}
	parsedSummary = summary
	parsedSummary.Scenarios = parsedSummary.Scenarios[:len(parsedSummary.Scenarios)-1]
	parsedSummary.Totals.Scenarios--
	if err := ValidateDrillEvidence(parsedSummary); err == nil {
		t.Fatal("expected missing drill scenario to fail validation")
	}
}

func TestCommandsAndHelpers(t *testing.T) {
	target := store.Target{Host: "edge.example.com", Port: 2222, User: "deployer", Engine: ir.EngineNginx, ConfigPath: "/etc/nginx/nginx.conf", ReloadCommand: "systemctl reload nginx", Sudo: true}
	if got := uploadCommand(target, "/tmp/it's.cfg"); !strings.HasPrefix(got, "cat > ") || !strings.Contains(got, "'\"'\"'") {
		t.Fatalf("unexpected upload command: %s", got)
	}
	if got := remoteValidateCommand(target, "/tmp/nginx.conf"); got != "nginx -t -c '/tmp/nginx.conf'" {
		t.Fatalf("unexpected nginx validate command: %s", got)
	}
	if got := remoteValidateCommand(store.Target{Engine: ir.EngineHAProxy}, "/tmp/haproxy.cfg"); got != "haproxy -c -f '/tmp/haproxy.cfg'" {
		t.Fatalf("unexpected haproxy validate command: %s", got)
	}
	if got := installCommand(target, "/tmp/nginx.conf"); !strings.HasPrefix(got, "sudo sh -lc ") {
		t.Fatalf("expected sudo install command: %s", got)
	}
	if got := cleanupCommand("/tmp/it's.cfg"); got != "rm -f '/tmp/it'\"'\"'s.cfg'" {
		t.Fatalf("unexpected cleanup command: %s", got)
	}
	if stepStatus(errors.New("bad"), true) != "failed" || stepStatus(nil, true) != "success" || stepStatus(nil, false) != "success" {
		t.Fatal("unexpected step status")
	}
	if errString(nil) != "" || errString(errors.New("bad")) != "bad" {
		t.Fatal("unexpected errString")
	}
	if hasFailed([]Step{{Status: "success"}}) || !hasFailed([]Step{{Status: "failed"}}) {
		t.Fatal("unexpected hasFailed")
	}
	sources := CredentialSources([]Step{{Credential: ""}, {Credential: "vault"}, {Credential: "vault"}, {Credential: "local_ssh"}})
	if strings.Join(sources, ",") != "vault,local_ssh" {
		t.Fatalf("unexpected credential sources: %v", sources)
	}
	rollbackStats := RollbackSummary([]Step{
		{Stage: "rollback", Status: "skipped"},
		{Stage: "rollback", Status: "success"},
		{Stage: "rollback", Status: "failed"},
		{Stage: "cleanup", Status: "success"},
	})
	if rollbackStats.Planned != 3 || rollbackStats.Attempted != 2 || rollbackStats.Succeeded != 1 || rollbackStats.Failed != 1 {
		t.Fatalf("unexpected rollback stats: %+v", rollbackStats)
	}
	cleanupStats := CleanupSummary([]Step{
		{Stage: "cleanup", Status: "skipped"},
		{Stage: "cleanup", Status: "success"},
		{Stage: "cleanup", Status: "failed"},
		{Stage: "rollback", Status: "failed"},
	})
	if cleanupStats.Planned != 3 || cleanupStats.Attempted != 2 || cleanupStats.Succeeded != 1 || cleanupStats.Failed != 1 {
		t.Fatalf("unexpected cleanup stats: %+v", cleanupStats)
	}
}

func TestSSHRunnerWithFakeSSH(t *testing.T) {
	dir := t.TempDir()
	oldPath := os.Getenv("PATH")
	t.Cleanup(func() { _ = os.Setenv("PATH", oldPath) })
	script := filepath.Join(dir, "ssh")
	body := "#!/bin/sh\ncat >/dev/null\necho fake-ssh \"$@\"\n"
	if runtime.GOOS == "windows" {
		script += ".bat"
		body = "@echo off\r\nmore > nul\r\necho fake-ssh %*\r\n"
	}
	if err := os.WriteFile(script, []byte(body), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Setenv("PATH", dir+string(os.PathListSeparator)+oldPath); err != nil {
		t.Fatal(err)
	}
	out, err := sshRunner(t.Context(), store.Target{Host: "host", Port: 22, User: "root"}, secrets.Secret{}, "echo ok", "config")
	if err != nil || !strings.Contains(out, "fake-ssh") {
		t.Fatalf("unexpected fake ssh result out=%q err=%v", out, err)
	}
	out, err = sshRunner(t.Context(), store.Target{Host: "host", Port: 2222, User: "deploy"}, secrets.Secret{}, uploadCommand(store.Target{}, "/tmp/mizan.cfg"), "generated config")
	if err != nil || !strings.Contains(out, "fake-ssh") || (runtime.GOOS != "windows" && (!strings.Contains(out, "cat >") || strings.Contains(out, "ssh -p 2222 deploy@host ssh"))) {
		t.Fatalf("unexpected fake upload out=%q err=%v", out, err)
	}
	out, err = sshRunner(t.Context(), store.Target{Host: "host", Port: 22, User: "root"}, secrets.Secret{Username: "vault", PrivateKey: "PRIVATE KEY"}, "echo ok", "")
	if err != nil || !strings.Contains(out, "fake-ssh") || !strings.Contains(out, "vault@host") {
		t.Fatalf("unexpected credential ssh result out=%q err=%v", out, err)
	}
}

func TestPrivateKeyFileErrors(t *testing.T) {
	oldCreate, oldWrite, oldChmod, oldRemove := createTempKeyFile, writeKeyFile, chmodKeyFile, removeKeyFile
	t.Cleanup(func() {
		createTempKeyFile, writeKeyFile, chmodKeyFile, removeKeyFile = oldCreate, oldWrite, oldChmod, oldRemove
	})
	credential := secrets.Secret{PrivateKey: "PRIVATE KEY"}
	createTempKeyFile = func() (string, error) { return "", errors.New("create failed") }
	if _, _, err := privateKeyFile(credential); err == nil || err.Error() != "create failed" {
		t.Fatalf("expected create error, got %v", err)
	}
	createTempKeyFile = oldCreate
	path := filepath.Join(t.TempDir(), "key")
	createTempKeyFile = func() (string, error) { return path, nil }
	writeKeyFile = func(string, []byte, os.FileMode) error { return errors.New("write failed") }
	if _, _, err := privateKeyFile(credential); err == nil || err.Error() != "write failed" {
		t.Fatalf("expected write error, got %v", err)
	}
	writeKeyFile = oldWrite
	chmodKeyFile = func(string, os.FileMode) error { return errors.New("chmod failed") }
	if _, _, err := privateKeyFile(credential); err == nil || err.Error() != "chmod failed" {
		t.Fatalf("expected chmod error, got %v", err)
	}
	createTempKeyFile = func() (string, error) { return "", errors.New("create failed") }
	if out, err := sshRunner(t.Context(), store.Target{Host: "host", Port: 22, User: "root"}, credential, "echo ok", ""); err == nil || out != "" {
		t.Fatalf("expected ssh runner key error out=%q err=%v", out, err)
	}
}

func TestDefaultCreateTempKeyFileError(t *testing.T) {
	badTemp := filepath.Join(t.TempDir(), "temp-file")
	if err := os.WriteFile(badTemp, []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("TMPDIR", badTemp)
	t.Setenv("TMP", badTemp)
	t.Setenv("TEMP", badTemp)
	t.Setenv("USERPROFILE", badTemp)
	if _, err := createTempKeyFile(); err == nil {
		t.Fatal("expected temp key creation error")
	}
}

func TestHTTPProbe(t *testing.T) {
	if err := httpProbe(t.Context(), "://bad"); err == nil {
		t.Fatal("expected request creation error")
	}
	if err := httpProbe(t.Context(), "http://127.0.0.1:1"); err == nil {
		t.Fatal("expected connection error")
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/fail" {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()
	if err := httpProbe(t.Context(), server.URL+"/fail"); err == nil {
		t.Fatal("expected status error")
	}
	if err := httpProbe(t.Context(), server.URL+"/ok"); err != nil {
		t.Fatalf("expected successful probe: %v", err)
	}
}

func TestProbeTarget(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()
	now := time.Date(2026, 4, 26, 10, 0, 0, 0, time.UTC)
	result, err := ProbeTarget(t.Context(), store.Target{ID: "t_1", Name: "edge", PostReloadProbe: "https://edge.example.com/healthz"}, func(context.Context, string) error {
		return nil
	}, func() time.Time { return now })
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "success" || result.URL != "https://edge.example.com/healthz" || result.CheckedAt != now.Format(time.RFC3339) {
		t.Fatalf("result=%+v", result)
	}
	result, err = ProbeTarget(t.Context(), store.Target{ID: "t_1", Name: "edge", MonitorEndpoint: "https://edge.example.com/status"}, func(context.Context, string) error {
		return errors.New("probe failed")
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "failed" || result.Message != "probe failed" || result.URL != "https://edge.example.com/status" {
		t.Fatalf("result=%+v", result)
	}
	result, err = ProbeTarget(t.Context(), store.Target{ID: "t_1", Name: "edge", PostReloadProbe: server.URL}, nil, nil)
	if err != nil || result.Status != "success" {
		t.Fatalf("expected default prober success result=%+v err=%v", result, err)
	}
	if _, err := ProbeTarget(t.Context(), store.Target{Name: "edge"}, nil, nil); err == nil {
		t.Fatal("expected missing endpoint error")
	}
}
